name: Deploy Frontend

on:
  push:
    paths:
      - "frontend-3rd-loan/**"
    branches:
      - "fe"
      # TODO: 최종에서는 fe -> main으로 바꾸기

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and deploy frontend Docker image
        run: |
          cd frontend-3rd-loan
          docker pull seonmin5/action-fe:1.0

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker stop action-fe || true
            docker rm action-fe || true
            docker run -d -p 80:3000 --name action-fe seonmin5/action-fe:1.0
